// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKF9JHEUTTi0mHEnBWy7_rIt1tZ3h27E4',
    appId: '1:331498996476:web:e3b3e2b6a173fac527cd79',
    messagingSenderId: '331498996476',
    projectId: 'food-ordering-app-6fa7a',
    authDomain: 'food-ordering-app-6fa7a.firebaseapp.com',
    storageBucket: 'food-ordering-app-6fa7a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO0DRy7i5JG_zosxG5wUtNPRhrIj7dsg0',
    appId: '1:331498996476:android:523b8285894dcdce27cd79',
    messagingSenderId: '331498996476',
    projectId: 'food-ordering-app-6fa7a',
    storageBucket: 'food-ordering-app-6fa7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhpwcQxErrOcTv_k42-7sYU5oIM4FIJoY',
    appId: '1:331498996476:ios:67a6f1297426b30e27cd79',
    messagingSenderId: '331498996476',
    projectId: 'food-ordering-app-6fa7a',
    storageBucket: 'food-ordering-app-6fa7a.firebasestorage.app',
    iosBundleId: 'com.example.code',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhpwcQxErrOcTv_k42-7sYU5oIM4FIJoY',
    appId: '1:331498996476:ios:67a6f1297426b30e27cd79',
    messagingSenderId: '331498996476',
    projectId: 'food-ordering-app-6fa7a',
    storageBucket: 'food-ordering-app-6fa7a.firebasestorage.app',
    iosBundleId: 'com.example.code',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKF9JHEUTTi0mHEnBWy7_rIt1tZ3h27E4',
    appId: '1:331498996476:web:c6d72c6d98edf92427cd79',
    messagingSenderId: '331498996476',
    projectId: 'food-ordering-app-6fa7a',
    authDomain: 'food-ordering-app-6fa7a.firebaseapp.com',
    storageBucket: 'food-ordering-app-6fa7a.firebasestorage.app',
  );
}
